import Head from "next/head";
import styles from "../styles/Home.module.css";
import Card from "../components/Card";
import { StatGroup, Stat, StatLabel, StatNumber, Text } from "@chakra-ui/react";
import { useFloorPrice } from "../hooks/useFloorPrice";

export default function Home() {
  const { data: peskyPenguinsMagicEden } = useFloorPrice({
    collection: "pesky_penguins",
    marketplace: "magicEden",
  });

  const { data: peskyPenguinsAlphaArt } = useFloorPrice({
    collection: "pesky-penguins",
    marketplace: "alphaArt",
  });

  const { data: danukiDojo } = useFloorPrice({
    collection: "danuki_dojo",
    marketplace: "magicEden",
  });

  const { data: SDB } = useFloorPrice({
    collection: "solana_droid_business",
    marketplace: "magicEden",
  });

  const { data: mechsOfSolana } = useFloorPrice({
    collection: "mechs_of_solana",
    marketplace: "magicEden",
  });

  const { data: spookeletons } = useFloorPrice({
    collection: "spookeletons",
    marketplace: "magicEden",
  });

  const { data: skeletonCrewSkulls } = useFloorPrice({
    collection: "skeleton_crew_skulls",
    marketplace: "magicEden",
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Floor tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Card title="Pesky penguin">
        <StatGroup justifyContent="space-between">
          <Stat>
            <StatLabel>Magic Eden</StatLabel>
            <StatNumber>{peskyPenguinsMagicEden}</StatNumber>
          </Stat>
          <Stat>
            <StatLabel>Alpha Art</StatLabel>
            <StatNumber>{peskyPenguinsAlphaArt}</StatNumber>
          </Stat>
          <Stat>
            <StatLabel>Digital Eyes</StatLabel>
            <Text>WIP</Text>
          </Stat>
        </StatGroup>
      </Card>

      <Card title="Solana Droid Business">
        <StatGroup justifyContent="space-between">
          <Stat>
            <StatLabel>Magic Eden</StatLabel>
            <StatNumber>{SDB}</StatNumber>
          </Stat>
        </StatGroup>
      </Card>

      <Card title="Danuki Dojo">
        <StatGroup justifyContent="space-between">
          <Stat>
            <StatLabel>Magic Eden</StatLabel>
            <StatNumber>{danukiDojo}</StatNumber>
          </Stat>
        </StatGroup>
      </Card>

      <Card title="Skeleton Crew Skulls">
        <StatGroup justifyContent="space-between">
          <Stat>
            <StatLabel>Magic Eden</StatLabel>
            <StatNumber>{skeletonCrewSkulls}</StatNumber>
          </Stat>
        </StatGroup>
      </Card>

      <Card title="Mechs of Solana">
        <StatGroup justifyContent="space-between">
          <Stat>
            <StatLabel>Magic Eden</StatLabel>
            <StatNumber>{mechsOfSolana}</StatNumber>
          </Stat>
        </StatGroup>
      </Card>

      <Card title="Spookeletons">
        <StatGroup justifyContent="space-between">
          <Stat>
            <StatLabel>Magic Eden</StatLabel>
            <StatNumber>{spookeletons}</StatNumber>
          </Stat>
        </StatGroup>
      </Card>
    </div>
  );
}
